version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: "wurstmeister/kafka:0.10.2.0" # Using a more stable version
    ports:
      - "9092:9092"
    hostname: kafka
    depends_on: # Modern replacement for 'links'
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Listens on all interfaces inside the container
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      # Advertises an address reachable from your host machine (localhost)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"

# 